// DO NOT EDIT THIS FILE. GENERATED BY xgen.

//go:build rp2350

package ticks

import (
	"embedded/mmio"
	"unsafe"

	"github.com/embeddedgo/pico/p/mmap"
)

type Periph struct {
	T [6]ST
}

func TICKS() *Periph { return (*Periph)(unsafe.Pointer(uintptr(mmap.TICKS_BASE))) }

func (p *Periph) BaseAddr() uintptr {
	return uintptr(unsafe.Pointer(p))
}

type ST struct {
	CTRL   mmio.R32[CTRL]
	CYCLES mmio.R32[CYCLES]
	COUNT  mmio.R32[COUNT]
}

type CTRL uint32

func ENABLE_(p *Periph, i int) mmio.RM32[CTRL]  { return mmio.RM32[CTRL]{&p.T[i].CTRL, ENABLE} }
func RUNNING_(p *Periph, i int) mmio.RM32[CTRL] { return mmio.RM32[CTRL]{&p.T[i].CTRL, RUNNING} }

type CYCLES uint32

type COUNT uint32
