// Code generated by xgen -g; DO NOT EDIT.

//go:build rp2350

package ticks

import (
	"embedded/mmio"
	"unsafe"

	"github.com/embeddedgo/pico/p/mmap"
)

type Periph struct {
	T [6]ST
}

func TICKS() *Periph { return (*Periph)(unsafe.Pointer(uintptr(mmap.TICKS_BASE))) }

func (p *Periph) BaseAddr() uintptr {
	return uintptr(unsafe.Pointer(p))
}

type ST struct {
	CTRL   mmio.R32[CTRL]
	CYCLES mmio.R32[uint32]
	COUNT  mmio.R32[uint32]
}

type CTRL uint32

func ENABLE_(p *Periph, i int) mmio.RM32[CTRL] { return mmio.RM32[CTRL]{R: &p.T[i].CTRL, Mask: ENABLE} }
func RUNNING_(p *Periph, i int) mmio.RM32[CTRL] {
	return mmio.RM32[CTRL]{R: &p.T[i].CTRL, Mask: RUNNING}
}
