// DO NOT EDIT THIS FILE. GENERATED BY svdxgen.

//go:build rp2350

// Package uart provides access to the registers of the UART peripheral.
//
// Instances:
//
//	UART0  UART0_BASE  -  UART0_IRQ
//	UART1  UART1_BASE  -  UART1_IRQ
//
// Registers:
//
//	0x000 32  UARTDR         Data Register, UARTDR
//	0x004 32  UARTRSR        Receive Status Register/Error Clear Register, UARTRSR/UARTECR
//	0x018 32  UARTFR         Flag Register, UARTFR
//	0x020 32  UARTILPR       IrDA Low-Power Counter Register, UARTILPR
//	0x024 32  UARTIBRD       Integer Baud Rate Register, UARTIBRD
//	0x028 32  UARTFBRD       Fractional Baud Rate Register, UARTFBRD
//	0x02C 32  UARTLCR_H      Line Control Register, UARTLCR_H
//	0x030 32  UARTCR         Control Register, UARTCR
//	0x034 32  UARTIFLS       Interrupt FIFO Level Select Register, UARTIFLS
//	0x038 32  UARTIMSC       Interrupt Mask Set/Clear Register, UARTIMSC
//	0x03C 32  UARTRIS        Raw Interrupt Status Register, UARTRIS
//	0x040 32  UARTMIS        Masked Interrupt Status Register, UARTMIS
//	0x044 32  UARTICR        Interrupt Clear Register, UARTICR
//	0x048 32  UARTDMACR      DMA Control Register, UARTDMACR
//	0xFE0 32  UARTPERIPHID0  UARTPeriphID0 Register
//	0xFE4 32  UARTPERIPHID1  UARTPeriphID1 Register
//	0xFE8 32  UARTPERIPHID2  UARTPeriphID2 Register
//	0xFEC 32  UARTPERIPHID3  UARTPeriphID3 Register
//	0xFF0 32  UARTPCELLID0   UARTPCellID0 Register
//	0xFF4 32  UARTPCELLID1   UARTPCellID1 Register
//	0xFF8 32  UARTPCELLID2   UARTPCellID2 Register
//	0xFFC 32  UARTPCELLID3   UARTPCellID3 Register
//
// Import:
//
//	github.com/embeddedgo/pico/p/mmap
package uart

const (
	DATA UARTDR = 0xFF << 0  //+ Receive (read) data character. Transmit (write) data character.
	FE   UARTDR = 0x01 << 8  //+ Framing error. When set to 1, it indicates that the received character did not have a valid stop bit (a valid stop bit is 1). In FIFO mode, this error is associated with the character at the top of the FIFO.
	PE   UARTDR = 0x01 << 9  //+ Parity error. When set to 1, it indicates that the parity of the received data character does not match the parity that the EPS and SPS bits in the Line Control Register, UARTLCR_H. In FIFO mode, this error is associated with the character at the top of the FIFO.
	BE   UARTDR = 0x01 << 10 //+ Break error. This bit is set to 1 if a break condition was detected, indicating that the received data input was held LOW for longer than a full-word transmission time (defined as start, data, parity and stop bits). In FIFO mode, this error is associated with the character at the top of the FIFO. When a break occurs, only one 0 character is loaded into the FIFO. The next character is only enabled after the receive data input goes to a 1 (marking state), and the next valid start bit is received.
	OE   UARTDR = 0x01 << 11 //+ Overrun error. This bit is set to 1 if data is received and the receive FIFO is already full. This is cleared to 0 once there is an empty space in the FIFO and a new character can be written to it.
)

const (
	DATAn = 0
	FEn   = 8
	PEn   = 9
	BEn   = 10
	OEn   = 11
)

const (
	FE UARTRSR = 0x01 << 0 //+ Framing error. When set to 1, it indicates that the received character did not have a valid stop bit (a valid stop bit is 1). This bit is cleared to 0 by a write to UARTECR. In FIFO mode, this error is associated with the character at the top of the FIFO.
	PE UARTRSR = 0x01 << 1 //+ Parity error. When set to 1, it indicates that the parity of the received data character does not match the parity that the EPS and SPS bits in the Line Control Register, UARTLCR_H. This bit is cleared to 0 by a write to UARTECR. In FIFO mode, this error is associated with the character at the top of the FIFO.
	BE UARTRSR = 0x01 << 2 //+ Break error. This bit is set to 1 if a break condition was detected, indicating that the received data input was held LOW for longer than a full-word transmission time (defined as start, data, parity, and stop bits). This bit is cleared to 0 after a write to UARTECR. In FIFO mode, this error is associated with the character at the top of the FIFO. When a break occurs, only one 0 character is loaded into the FIFO. The next character is only enabled after the receive data input goes to a 1 (marking state) and the next valid start bit is received.
	OE UARTRSR = 0x01 << 3 //+ Overrun error. This bit is set to 1 if data is received and the FIFO is already full. This bit is cleared to 0 by a write to UARTECR. The FIFO contents remain valid because no more data is written when the FIFO is full, only the contents of the shift register are overwritten. The CPU must now read the data, to empty the FIFO.
)

const (
	FEn = 0
	PEn = 1
	BEn = 2
	OEn = 3
)

const (
	CTS  UARTFR = 0x01 << 0 //+ Clear to send. This bit is the complement of the UART clear to send, nUARTCTS, modem status input. That is, the bit is 1 when nUARTCTS is LOW.
	DSR  UARTFR = 0x01 << 1 //+ Data set ready. This bit is the complement of the UART data set ready, nUARTDSR, modem status input. That is, the bit is 1 when nUARTDSR is LOW.
	DCD  UARTFR = 0x01 << 2 //+ Data carrier detect. This bit is the complement of the UART data carrier detect, nUARTDCD, modem status input. That is, the bit is 1 when nUARTDCD is LOW.
	BUSY UARTFR = 0x01 << 3 //+ UART busy. If this bit is set to 1, the UART is busy transmitting data. This bit remains set until the complete byte, including all the stop bits, has been sent from the shift register. This bit is set as soon as the transmit FIFO becomes non-empty, regardless of whether the UART is enabled or not.
	RXFE UARTFR = 0x01 << 4 //+ Receive FIFO empty. The meaning of this bit depends on the state of the FEN bit in the UARTLCR_H Register. If the FIFO is disabled, this bit is set when the receive holding register is empty. If the FIFO is enabled, the RXFE bit is set when the receive FIFO is empty.
	TXFF UARTFR = 0x01 << 5 //+ Transmit FIFO full. The meaning of this bit depends on the state of the FEN bit in the UARTLCR_H Register. If the FIFO is disabled, this bit is set when the transmit holding register is full. If the FIFO is enabled, the TXFF bit is set when the transmit FIFO is full.
	RXFF UARTFR = 0x01 << 6 //+ Receive FIFO full. The meaning of this bit depends on the state of the FEN bit in the UARTLCR_H Register. If the FIFO is disabled, this bit is set when the receive holding register is full. If the FIFO is enabled, the RXFF bit is set when the receive FIFO is full.
	TXFE UARTFR = 0x01 << 7 //+ Transmit FIFO empty. The meaning of this bit depends on the state of the FEN bit in the Line Control Register, UARTLCR_H. If the FIFO is disabled, this bit is set when the transmit holding register is empty. If the FIFO is enabled, the TXFE bit is set when the transmit FIFO is empty. This bit does not indicate if there is data in the transmit shift register.
	RI   UARTFR = 0x01 << 8 //+ Ring indicator. This bit is the complement of the UART ring indicator, nUARTRI, modem status input. That is, the bit is 1 when nUARTRI is LOW.
)

const (
	CTSn  = 0
	DSRn  = 1
	DCDn  = 2
	BUSYn = 3
	RXFEn = 4
	TXFFn = 5
	RXFFn = 6
	TXFEn = 7
	RIn   = 8
)

const (
	BRK  UARTLCR_H = 0x01 << 0 //+ Send break. If this bit is set to 1, a low-level is continually output on the UARTTXD output, after completing transmission of the current character. For the proper execution of the break command, the software must set this bit for at least two complete frames. For normal use, this bit must be cleared to 0.
	PEN  UARTLCR_H = 0x01 << 1 //+ Parity enable: 0 = parity is disabled and no parity bit added to the data frame 1 = parity checking and generation is enabled.
	EPS  UARTLCR_H = 0x01 << 2 //+ Even parity select. Controls the type of parity the UART uses during transmission and reception: 0 = odd parity. The UART generates or checks for an odd number of 1s in the data and parity bits. 1 = even parity. The UART generates or checks for an even number of 1s in the data and parity bits. This bit has no effect when the PEN bit disables parity checking and generation.
	STP2 UARTLCR_H = 0x01 << 3 //+ Two stop bits select. If this bit is set to 1, two stop bits are transmitted at the end of the frame. The receive logic does not check for two stop bits being received.
	FEN  UARTLCR_H = 0x01 << 4 //+ Enable FIFOs: 0 = FIFOs are disabled (character mode) that is, the FIFOs become 1-byte-deep holding registers 1 = transmit and receive FIFO buffers are enabled (FIFO mode).
	WLEN UARTLCR_H = 0x03 << 5 //+ Word length. These bits indicate the number of data bits transmitted or received in a frame as follows: b11 = 8 bits b10 = 7 bits b01 = 6 bits b00 = 5 bits.
	SPS  UARTLCR_H = 0x01 << 7 //+ Stick parity select. 0 = stick parity is disabled 1 = either: * if the EPS bit is 0 then the parity bit is transmitted and checked as a 1 * if the EPS bit is 1 then the parity bit is transmitted and checked as a 0. This bit has no effect when the PEN bit disables parity checking and generation.
)

const (
	BRKn  = 0
	PENn  = 1
	EPSn  = 2
	STP2n = 3
	FENn  = 4
	WLENn = 5
	SPSn  = 7
)

const (
	UARTEN UARTCR = 0x01 << 0  //+ UART enable: 0 = UART is disabled. If the UART is disabled in the middle of transmission or reception, it completes the current character before stopping. 1 = the UART is enabled. Data transmission and reception occurs for either UART signals or SIR signals depending on the setting of the SIREN bit.
	SIREN  UARTCR = 0x01 << 1  //+ SIR enable: 0 = IrDA SIR ENDEC is disabled. nSIROUT remains LOW (no light pulse generated), and signal transitions on SIRIN have no effect. 1 = IrDA SIR ENDEC is enabled. Data is transmitted and received on nSIROUT and SIRIN. UARTTXD remains HIGH, in the marking state. Signal transitions on UARTRXD or modem status inputs have no effect. This bit has no effect if the UARTEN bit disables the UART.
	SIRLP  UARTCR = 0x01 << 2  //+ SIR low-power IrDA mode. This bit selects the IrDA encoding mode. If this bit is cleared to 0, low-level bits are transmitted as an active high pulse with a width of 3 / 16th of the bit period. If this bit is set to 1, low-level bits are transmitted with a pulse width that is 3 times the period of the IrLPBaud16 input signal, regardless of the selected bit rate. Setting this bit uses less power, but might reduce transmission distances.
	LBE    UARTCR = 0x01 << 7  //+ Loopback enable. If this bit is set to 1 and the SIREN bit is set to 1 and the SIRTEST bit in the Test Control Register, UARTTCR is set to 1, then the nSIROUT path is inverted, and fed through to the SIRIN path. The SIRTEST bit in the test register must be set to 1 to override the normal half-duplex SIR operation. This must be the requirement for accessing the test registers during normal operation, and SIRTEST must be cleared to 0 when loopback testing is finished. This feature reduces the amount of external coupling required during system test. If this bit is set to 1, and the SIRTEST bit is set to 0, the UARTTXD path is fed through to the UARTRXD path. In either SIR mode or UART mode, when this bit is set, the modem outputs are also fed through to the modem inputs. This bit is cleared to 0 on reset, to disable loopback.
	TXE    UARTCR = 0x01 << 8  //+ Transmit enable. If this bit is set to 1, the transmit section of the UART is enabled. Data transmission occurs for either UART signals, or SIR signals depending on the setting of the SIREN bit. When the UART is disabled in the middle of transmission, it completes the current character before stopping.
	RXE    UARTCR = 0x01 << 9  //+ Receive enable. If this bit is set to 1, the receive section of the UART is enabled. Data reception occurs for either UART signals or SIR signals depending on the setting of the SIREN bit. When the UART is disabled in the middle of reception, it completes the current character before stopping.
	DTR    UARTCR = 0x01 << 10 //+ Data transmit ready. This bit is the complement of the UART data transmit ready, nUARTDTR, modem status output. That is, when the bit is programmed to a 1 then nUARTDTR is LOW.
	RTS    UARTCR = 0x01 << 11 //+ Request to send. This bit is the complement of the UART request to send, nUARTRTS, modem status output. That is, when the bit is programmed to a 1 then nUARTRTS is LOW.
	OUT1   UARTCR = 0x01 << 12 //+ This bit is the complement of the UART Out1 (nUARTOut1) modem status output. That is, when the bit is programmed to a 1 the output is 0. For DTE this can be used as Data Carrier Detect (DCD).
	OUT2   UARTCR = 0x01 << 13 //+ This bit is the complement of the UART Out2 (nUARTOut2) modem status output. That is, when the bit is programmed to a 1, the output is 0. For DTE this can be used as Ring Indicator (RI).
	RTSEN  UARTCR = 0x01 << 14 //+ RTS hardware flow control enable. If this bit is set to 1, RTS hardware flow control is enabled. Data is only requested when there is space in the receive FIFO for it to be received.
	CTSEN  UARTCR = 0x01 << 15 //+ CTS hardware flow control enable. If this bit is set to 1, CTS hardware flow control is enabled. Data is only transmitted when the nUARTCTS signal is asserted.
)

const (
	UARTENn = 0
	SIRENn  = 1
	SIRLPn  = 2
	LBEn    = 7
	TXEn    = 8
	RXEn    = 9
	DTRn    = 10
	RTSn    = 11
	OUT1n   = 12
	OUT2n   = 13
	RTSENn  = 14
	CTSENn  = 15
)

const (
	TXIFLSEL UARTIFLS = 0x07 << 0 //+ Transmit interrupt FIFO level select. The trigger points for the transmit interrupt are as follows: b000 = Transmit FIFO becomes <= 1 / 8 full b001 = Transmit FIFO becomes <= 1 / 4 full b010 = Transmit FIFO becomes <= 1 / 2 full b011 = Transmit FIFO becomes <= 3 / 4 full b100 = Transmit FIFO becomes <= 7 / 8 full b101-b111 = reserved.
	RXIFLSEL UARTIFLS = 0x07 << 3 //+ Receive interrupt FIFO level select. The trigger points for the receive interrupt are as follows: b000 = Receive FIFO becomes >= 1 / 8 full b001 = Receive FIFO becomes >= 1 / 4 full b010 = Receive FIFO becomes >= 1 / 2 full b011 = Receive FIFO becomes >= 3 / 4 full b100 = Receive FIFO becomes >= 7 / 8 full b101-b111 = reserved.
)

const (
	TXIFLSELn = 0
	RXIFLSELn = 3
)

const (
	RIMIM  UARTIMSC = 0x01 << 0  //+ nUARTRI modem interrupt mask. A read returns the current mask for the UARTRIINTR interrupt. On a write of 1, the mask of the UARTRIINTR interrupt is set. A write of 0 clears the mask.
	CTSMIM UARTIMSC = 0x01 << 1  //+ nUARTCTS modem interrupt mask. A read returns the current mask for the UARTCTSINTR interrupt. On a write of 1, the mask of the UARTCTSINTR interrupt is set. A write of 0 clears the mask.
	DCDMIM UARTIMSC = 0x01 << 2  //+ nUARTDCD modem interrupt mask. A read returns the current mask for the UARTDCDINTR interrupt. On a write of 1, the mask of the UARTDCDINTR interrupt is set. A write of 0 clears the mask.
	DSRMIM UARTIMSC = 0x01 << 3  //+ nUARTDSR modem interrupt mask. A read returns the current mask for the UARTDSRINTR interrupt. On a write of 1, the mask of the UARTDSRINTR interrupt is set. A write of 0 clears the mask.
	RXIM   UARTIMSC = 0x01 << 4  //+ Receive interrupt mask. A read returns the current mask for the UARTRXINTR interrupt. On a write of 1, the mask of the UARTRXINTR interrupt is set. A write of 0 clears the mask.
	TXIM   UARTIMSC = 0x01 << 5  //+ Transmit interrupt mask. A read returns the current mask for the UARTTXINTR interrupt. On a write of 1, the mask of the UARTTXINTR interrupt is set. A write of 0 clears the mask.
	RTIM   UARTIMSC = 0x01 << 6  //+ Receive timeout interrupt mask. A read returns the current mask for the UARTRTINTR interrupt. On a write of 1, the mask of the UARTRTINTR interrupt is set. A write of 0 clears the mask.
	FEIM   UARTIMSC = 0x01 << 7  //+ Framing error interrupt mask. A read returns the current mask for the UARTFEINTR interrupt. On a write of 1, the mask of the UARTFEINTR interrupt is set. A write of 0 clears the mask.
	PEIM   UARTIMSC = 0x01 << 8  //+ Parity error interrupt mask. A read returns the current mask for the UARTPEINTR interrupt. On a write of 1, the mask of the UARTPEINTR interrupt is set. A write of 0 clears the mask.
	BEIM   UARTIMSC = 0x01 << 9  //+ Break error interrupt mask. A read returns the current mask for the UARTBEINTR interrupt. On a write of 1, the mask of the UARTBEINTR interrupt is set. A write of 0 clears the mask.
	OEIM   UARTIMSC = 0x01 << 10 //+ Overrun error interrupt mask. A read returns the current mask for the UARTOEINTR interrupt. On a write of 1, the mask of the UARTOEINTR interrupt is set. A write of 0 clears the mask.
)

const (
	RIMIMn  = 0
	CTSMIMn = 1
	DCDMIMn = 2
	DSRMIMn = 3
	RXIMn   = 4
	TXIMn   = 5
	RTIMn   = 6
	FEIMn   = 7
	PEIMn   = 8
	BEIMn   = 9
	OEIMn   = 10
)

const (
	RIRMIS  UARTRIS = 0x01 << 0  //+ nUARTRI modem interrupt status. Returns the raw interrupt state of the UARTRIINTR interrupt.
	CTSRMIS UARTRIS = 0x01 << 1  //+ nUARTCTS modem interrupt status. Returns the raw interrupt state of the UARTCTSINTR interrupt.
	DCDRMIS UARTRIS = 0x01 << 2  //+ nUARTDCD modem interrupt status. Returns the raw interrupt state of the UARTDCDINTR interrupt.
	DSRRMIS UARTRIS = 0x01 << 3  //+ nUARTDSR modem interrupt status. Returns the raw interrupt state of the UARTDSRINTR interrupt.
	RXRIS   UARTRIS = 0x01 << 4  //+ Receive interrupt status. Returns the raw interrupt state of the UARTRXINTR interrupt.
	TXRIS   UARTRIS = 0x01 << 5  //+ Transmit interrupt status. Returns the raw interrupt state of the UARTTXINTR interrupt.
	RTRIS   UARTRIS = 0x01 << 6  //+ Receive timeout interrupt status. Returns the raw interrupt state of the UARTRTINTR interrupt. a
	FERIS   UARTRIS = 0x01 << 7  //+ Framing error interrupt status. Returns the raw interrupt state of the UARTFEINTR interrupt.
	PERIS   UARTRIS = 0x01 << 8  //+ Parity error interrupt status. Returns the raw interrupt state of the UARTPEINTR interrupt.
	BERIS   UARTRIS = 0x01 << 9  //+ Break error interrupt status. Returns the raw interrupt state of the UARTBEINTR interrupt.
	OERIS   UARTRIS = 0x01 << 10 //+ Overrun error interrupt status. Returns the raw interrupt state of the UARTOEINTR interrupt.
)

const (
	RIRMISn  = 0
	CTSRMISn = 1
	DCDRMISn = 2
	DSRRMISn = 3
	RXRISn   = 4
	TXRISn   = 5
	RTRISn   = 6
	FERISn   = 7
	PERISn   = 8
	BERISn   = 9
	OERISn   = 10
)

const (
	RIMMIS  UARTMIS = 0x01 << 0  //+ nUARTRI modem masked interrupt status. Returns the masked interrupt state of the UARTRIINTR interrupt.
	CTSMMIS UARTMIS = 0x01 << 1  //+ nUARTCTS modem masked interrupt status. Returns the masked interrupt state of the UARTCTSINTR interrupt.
	DCDMMIS UARTMIS = 0x01 << 2  //+ nUARTDCD modem masked interrupt status. Returns the masked interrupt state of the UARTDCDINTR interrupt.
	DSRMMIS UARTMIS = 0x01 << 3  //+ nUARTDSR modem masked interrupt status. Returns the masked interrupt state of the UARTDSRINTR interrupt.
	RXMIS   UARTMIS = 0x01 << 4  //+ Receive masked interrupt status. Returns the masked interrupt state of the UARTRXINTR interrupt.
	TXMIS   UARTMIS = 0x01 << 5  //+ Transmit masked interrupt status. Returns the masked interrupt state of the UARTTXINTR interrupt.
	RTMIS   UARTMIS = 0x01 << 6  //+ Receive timeout masked interrupt status. Returns the masked interrupt state of the UARTRTINTR interrupt.
	FEMIS   UARTMIS = 0x01 << 7  //+ Framing error masked interrupt status. Returns the masked interrupt state of the UARTFEINTR interrupt.
	PEMIS   UARTMIS = 0x01 << 8  //+ Parity error masked interrupt status. Returns the masked interrupt state of the UARTPEINTR interrupt.
	BEMIS   UARTMIS = 0x01 << 9  //+ Break error masked interrupt status. Returns the masked interrupt state of the UARTBEINTR interrupt.
	OEMIS   UARTMIS = 0x01 << 10 //+ Overrun error masked interrupt status. Returns the masked interrupt state of the UARTOEINTR interrupt.
)

const (
	RIMMISn  = 0
	CTSMMISn = 1
	DCDMMISn = 2
	DSRMMISn = 3
	RXMISn   = 4
	TXMISn   = 5
	RTMISn   = 6
	FEMISn   = 7
	PEMISn   = 8
	BEMISn   = 9
	OEMISn   = 10
)

const (
	RIMIC  UARTICR = 0x01 << 0  //+ nUARTRI modem interrupt clear. Clears the UARTRIINTR interrupt.
	CTSMIC UARTICR = 0x01 << 1  //+ nUARTCTS modem interrupt clear. Clears the UARTCTSINTR interrupt.
	DCDMIC UARTICR = 0x01 << 2  //+ nUARTDCD modem interrupt clear. Clears the UARTDCDINTR interrupt.
	DSRMIC UARTICR = 0x01 << 3  //+ nUARTDSR modem interrupt clear. Clears the UARTDSRINTR interrupt.
	RXIC   UARTICR = 0x01 << 4  //+ Receive interrupt clear. Clears the UARTRXINTR interrupt.
	TXIC   UARTICR = 0x01 << 5  //+ Transmit interrupt clear. Clears the UARTTXINTR interrupt.
	RTIC   UARTICR = 0x01 << 6  //+ Receive timeout interrupt clear. Clears the UARTRTINTR interrupt.
	FEIC   UARTICR = 0x01 << 7  //+ Framing error interrupt clear. Clears the UARTFEINTR interrupt.
	PEIC   UARTICR = 0x01 << 8  //+ Parity error interrupt clear. Clears the UARTPEINTR interrupt.
	BEIC   UARTICR = 0x01 << 9  //+ Break error interrupt clear. Clears the UARTBEINTR interrupt.
	OEIC   UARTICR = 0x01 << 10 //+ Overrun error interrupt clear. Clears the UARTOEINTR interrupt.
)

const (
	RIMICn  = 0
	CTSMICn = 1
	DCDMICn = 2
	DSRMICn = 3
	RXICn   = 4
	TXICn   = 5
	RTICn   = 6
	FEICn   = 7
	PEICn   = 8
	BEICn   = 9
	OEICn   = 10
)

const (
	RXDMAE   UARTDMACR = 0x01 << 0 //+ Receive DMA enable. If this bit is set to 1, DMA for the receive FIFO is enabled.
	TXDMAE   UARTDMACR = 0x01 << 1 //+ Transmit DMA enable. If this bit is set to 1, DMA for the transmit FIFO is enabled.
	DMAONERR UARTDMACR = 0x01 << 2 //+ DMA on error. If this bit is set to 1, the DMA receive request outputs, UARTRXDMASREQ or UARTRXDMABREQ, are disabled when the UART error interrupt is asserted.
)

const (
	RXDMAEn   = 0
	TXDMAEn   = 1
	DMAONERRn = 2
)

const (
	PARTNUMBER1 UARTPERIPHID1 = 0x0F << 0 //+ These bits read back as 0x0
	DESIGNER0   UARTPERIPHID1 = 0x0F << 4 //+ These bits read back as 0x1
)

const (
	PARTNUMBER1n = 0
	DESIGNER0n   = 4
)

const (
	DESIGNER1 UARTPERIPHID2 = 0x0F << 0 //+ These bits read back as 0x4
	REVISION  UARTPERIPHID2 = 0x0F << 4 //+ This field depends on the revision of the UART: r1p0 0x0 r1p1 0x1 r1p3 0x2 r1p4 0x2 r1p5 0x3
)

const (
	DESIGNER1n = 0
	REVISIONn  = 4
)
