// DO NOT EDIT THIS FILE. GENERATED BY svdxgen.

//go:build rp2350

// Package irq provides the list of supported external interrupts.
package irq

import "embedded/rtos"

const (
	TIMER0_IRQ_0     rtos.IRQ = 0
	TIMER0_IRQ_1     rtos.IRQ = 1
	TIMER0_IRQ_2     rtos.IRQ = 2
	TIMER0_IRQ_3     rtos.IRQ = 3
	TIMER1_IRQ_0     rtos.IRQ = 4
	TIMER1_IRQ_1     rtos.IRQ = 5
	TIMER1_IRQ_2     rtos.IRQ = 6
	TIMER1_IRQ_3     rtos.IRQ = 7
	PWM_IRQ_WRAP_0   rtos.IRQ = 8
	PWM_IRQ_WRAP_1   rtos.IRQ = 9
	DMA_IRQ_0        rtos.IRQ = 10
	DMA_IRQ_1        rtos.IRQ = 11
	DMA_IRQ_2        rtos.IRQ = 12
	DMA_IRQ_3        rtos.IRQ = 13
	USBCTRL_IRQ      rtos.IRQ = 14
	PIO0_IRQ_0       rtos.IRQ = 15
	PIO0_IRQ_1       rtos.IRQ = 16
	PIO1_IRQ_0       rtos.IRQ = 17
	PIO1_IRQ_1       rtos.IRQ = 18
	PIO2_IRQ_0       rtos.IRQ = 19
	PIO2_IRQ_1       rtos.IRQ = 20
	IO_IRQ_BANK0     rtos.IRQ = 21
	IO_IRQ_BANK0_NS  rtos.IRQ = 22
	IO_IRQ_QSPI      rtos.IRQ = 23
	IO_IRQ_QSPI_NS   rtos.IRQ = 24
	SIO_IRQ_FIFO     rtos.IRQ = 25
	SIO_IRQ_BELL     rtos.IRQ = 26
	SIO_IRQ_FIFO_NS  rtos.IRQ = 27
	SIO_IRQ_BELL_NS  rtos.IRQ = 28
	SIO_IRQ_MTIMECMP rtos.IRQ = 29
	CLOCKS_IRQ       rtos.IRQ = 30
	SPI0_IRQ         rtos.IRQ = 31
	SPI1_IRQ         rtos.IRQ = 32
	UART0_IRQ        rtos.IRQ = 33
	UART1_IRQ        rtos.IRQ = 34
	ADC_IRQ_FIFO     rtos.IRQ = 35
	I2C0_IRQ         rtos.IRQ = 36
	I2C1_IRQ         rtos.IRQ = 37
	OTP_IRQ          rtos.IRQ = 38
	TRNG_IRQ         rtos.IRQ = 39
	PLL_SYS_IRQ      rtos.IRQ = 42
	PLL_USB_IRQ      rtos.IRQ = 43
	POWMAN_IRQ_POW   rtos.IRQ = 44
	POWMAN_IRQ_TIMER rtos.IRQ = 45
)
