// DO NOT EDIT THIS FILE. GENERATED BY xgen.

//go:build rp2350

package xosc

import (
	"embedded/mmio"
	"unsafe"

	"github.com/embeddedgo/pico/p/mmap"
)

type Periph struct {
	CTRL    mmio.R32[CTRL]
	STATUS  mmio.R32[CTRL]
	DORMANT mmio.R32[uint32]
	STARTUP mmio.R32[STARTUP]
	COUNT   mmio.R32[uint32]
}

func XOSC() *Periph { return (*Periph)(unsafe.Pointer(uintptr(mmap.XOSC_BASE))) }

func (p *Periph) BaseAddr() uintptr {
	return uintptr(unsafe.Pointer(p))
}

type CTRL uint32

func FREQ_RANGE_(p *Periph) mmio.RM32[CTRL] { return mmio.RM32[CTRL]{&p.CTRL, FREQ_RANGE} }
func EN_(p *Periph) mmio.RM32[CTRL]         { return mmio.RM32[CTRL]{&p.CTRL, EN} }

type STARTUP uint32

func DELAY_(p *Periph) mmio.RM32[STARTUP] { return mmio.RM32[STARTUP]{&p.STARTUP, DELAY} }
func X4_(p *Periph) mmio.RM32[STARTUP]    { return mmio.RM32[STARTUP]{&p.STARTUP, X4} }
