// Code generated by egtool pioasm; DO NOT EDIT.

package main

import "github.com/embeddedgo/pico/hal/pio"

/// Global symbols ///
const (
)

/// Program bt656 ///

// Symbols
const (
)

// Labels
const (
)

// Code
const pioProg_bt656 pio.StringProgram = "" +
	"\xff" + //             origin:    -1
	"\x00\x01\x00" + //     CLKDIV:    1
	"\x60\x70\x01\x00" + // EXECCTRL:  wrap=0-23
	"\x3f\x00\x00\x00" + // SHIFTCTRL: fifo=txrx
	"\xf0\x1f" + //         PINCTRL:   sideset=0
	// Instructions:
	//              .wrap_target
	"\xc3\xa0" + //  0:  mov    isr, null
	"\x28\x20" + //  1:  wait   0 pin, 8
	"\xa8\x20" + //  2:  wait   1 pin, 8
	"\x08\x40" + //  3:  in     pins, 8
	"\x26\xa0" + //  4:  mov    x, isr
	"\x40\x00" + //  5:  jmp    x--, 0
	"\x28\x20" + //  6:  wait   0 pin, 8
	"\xa8\x20" + //  7:  wait   1 pin, 8
	"\x08\x40" + //  8:  in     pins, 8
	"\x26\xa0" + //  9:  mov    x, isr
	"\x40\x00" + // 10:  jmp    x--, 0
	"\x28\x20" + // 11:  wait   0 pin, 8
	"\xa8\x20" + // 12:  wait   1 pin, 8
	"\x04\x40" + // 13:  in     pins, 4
	"\x26\xa0" + // 14:  mov    x, isr
	"\x31\x00" + // 15:  jmp    !x, 17
	"\xa0\x00" + // 16:  jmp    x != y, 0
	"\x20\x80" + // 17:  push   block
	"\x27\xa0" + // 18:  mov    x, osr
	"\x28\x20" + // 19:  wait   0 pin, 8
	"\xa8\x20" + // 20:  wait   1 pin, 8
	"\x08\x40" + // 21:  in     pins, 8
	"\x60\x80" + // 22:  push   iffull block
	"\x53\x00" + // 23:  jmp    x--, 19
	//              .wrap
	""
