// Code generated by egtool pioasm; DO NOT EDIT.

package main

import "github.com/embeddedgo/pico/hal/pio"

/// Global symbols ///
const (
	pioSym_aaa = 15
)

/// Program squarewave ///

// Symbols
const (
	pioSym_squarewave_bbb = 4
)

// Labels
const (
)

// Code
const pioProg_squarewave pio.StringProgram = "" +
	"\xff" + //             origin:    -1
	"\x00\x01\x00" + //     CLKDIV:    1
	"\x60\x30\x00\x00" + // EXECCTRL:  wrap=0-3
	"\x1f\x00\x00\x00" + // SHIFTCTRL: fifo=txrx
	"\xf0\x1f" + //         PINCTRL:   sideset=0
	// Instructions:
	//              .wrap_target
	"\x81\xe0" + //  0:  set    pindirs, 1
	"\x01\xe1" + //  1:  set    pins, 1                [1]
	"\x00\xe0" + //  2:  set    pins, 0
	"\x01\x00" + //  3:  jmp    1
	//              .wrap
	""

/// Program pull_example1 ///

// Symbols
const (
)

// Labels
const (
	pioLab_pull_example1_entry_point = 1
)

// Code
const pioProg_pull_example1 pio.StringProgram = "" +
	"\xff" + //             origin:    -1
	"\x00\x01\x00" + //     CLKDIV:    1
	"\x60\x50\x00\x00" + // EXECCTRL:  wrap=0-5
	"\x1f\x00\x00\x00" + // SHIFTCTRL: fifo=txrx
	"\xf0\x1f" + //         PINCTRL:   sideset=0
	// Instructions:
	//              .wrap_target
	"\x08\x60" + //  0:  out    pins, 8
	"\xa0\x80" + //  1:  pull   block
	"\x08\x61" + //  2:  out    pins, 8                [1]
	"\x08\x61" + //  3:  out    pins, 8                [1]
	"\x08\x60" + //  4:  out    pins, 8
	"\x00\x00" + //  5:  jmp    0
	//              .wrap
	""

/// Program txOnlySPI ///

// Symbols
const (
)

// Labels
const (
)

// Code
const pioProg_txOnlySPI pio.StringProgram = "" +
	"\xff" + //             origin:    -1
	"\x00\x01\x00" + //     CLKDIV:    1
	"\xe0\x20\x00\x00" + // EXECCTRL:  wrap=1-2
	"\x1f\x00\x0a\x00" + // SHIFTCTRL: fifo=txrx out=,right,32,auto
	"\x00\x3e" + //         PINCTRL:   sideset=1 out=32
	// Instructions:
	"\x83\xe0" + //  0:  set    pindirs, 3      side 0
	//              .wrap_target
	"\x01\x60" + //  1:  out    pins, 1         side 0
	"\x42\xb0" + //  2:  nop                    side 1
	//              .wrap
	""
